IO2019TEAM-43 Add static analysis plugins: checkstyle, pmd, spotbugs.…
papaya-agh/papaya-backend pull request #16
Opened 2019-04-08 14:29 UTC by Sopel97

Wszystkie raporty sa generowane w formacie html w [data/web]/build/reports/...

2019-04-08 16:20 UTC, jplewa commented
Popatrzę jeszcze dokładniej :) Patrzyłeś może na coś do Groovy'ego (skoro mamy testy w Spocku)? Na pewno jest ten codenarc i ja nie mam z nim traumatycznych doświadczeń

Generalnie w Groovy'ego nikt nigdy nie umie, a codenarc fajnie krzyczy o średniki, pisanie `cośtam.pole` zamiast `cośtam.getPole()` oraz cuda typu inicjalizowanie map w formie `= [:]`

2019-04-08 17:21 UTC, Sopel97 commented
ogarne tego spocka to jeszcze popatrze na tego codenarc

2019-04-08 17:25 UTC, jplewa commented
> ogarne tego spocka to jeszcze popatrze na tego codenarc, bo mi nie pasowalo ze to do grooviego, ale ze spock to groovy to by nawet mialo sens

Jasne :) Spock to Groovy (taka skryptowo-nieskryptowa Java). Na stronie mają bardzo spoko wprowadzenie jakby co: http://spockframework.org/spock/docs/1.0/spock_primer.html

2019-04-08 18:59 UTC, Sopel97 commented
dodany codenarc, musialem wyrzucic 'rule' dotyczace javadoca bo ich z jakiegos powodu nie ma tak na prawde, i zmienilem regexa dla finalnych lokalnych zmiennych

2019-04-08 20:52 UTC, jplewa requested changes

2019-04-08 20:52 UTC, jplewa commented on config/checkstyle/checkstyle.xml
> +    </module>
Ups, sorki, całe to `IllegalImport` jest do wywalenia - zapomniałam, że to tu jest (dziwactwa Androida akurat)

2019-04-08 20:52 UTC, jplewa commented on config/checkstyle/checkstyle.xml
> +    <module name="MagicNumber" />
Tu nam sporo krzyczy o te wszystkie `@Column(length = x)`, także proponuję:
```
<module name="MagicNumber">
  <property name="ignoreAnnotation" value="true"/>
</module>
```

2019-04-08 21:29 UTC, jplewa commented
Generalnie dodanie `startParameter.continueOnFailure = true` do `settings.gradle` jest chyba spoko pomysłem, bo wtedy przechodzi do końca, nawet jak gdzieś po drodze będzie fail

2019-04-09 14:20 UTC, jplewa commented
Te wspólne zależności można w ogóle przenieść do `build.gradle` w roocie projektu:

<details><summary>O takie coś działa</summary>

```
buildscript {
    repositories { mavenCentral() }
}

plugins {
    id 'checkstyle'
    id 'pmd'
    id 'com.github.spotbugs' version '1.7.1'
    id 'codenarc'
}

subprojects {

    repositories {
        mavenCentral()
    }

    apply plugin: "checkstyle"

    spotbugs {
        effort = "max"
        reportLevel = "medium"
        includeFilter = rootProject.file("config/spotbugs/exclude.xml")
    }

    tasks.withType(com.github.spotbugs.SpotBugsTask) {
        reports {
            xml.enabled = false
            html.enabled = true
        }
    }

    tasks.withType(CodeNarc) {
        configFile = rootProject.file("config/codenarc/ruleset.groovy")
    }

    pmd {
        ruleSetFiles = rootProject.files("config/pmd/ruleset.xml")
    }
}
```

</details>

I wtedy można je wywalić z tych `build.gradle` w modułach

2019-04-09 14:24 UTC, jplewa commented
Te wspólne zależności można w ogóle przenieść do `build.gradle` w roocie projektu:

<details><summary>O takie coś działa (tutaj jest magiczny rozwijany blok kodu)</summary>

```
buildscript {
    repositories { mavenCentral() }
}

plugins {
    id 'checkstyle'
    id 'pmd'
    id 'com.github.spotbugs' version '1.7.1'
    id 'codenarc'
}

subprojects {

    repositories {
        mavenCentral()
    }

    apply plugin: "checkstyle"
    apply plugin: "pmd"
    apply plugin: "com.github.spotbugs"
    apply plugin: "codenarc"

    spotbugs {
        effort = "max"
        reportLevel = "medium"
        includeFilter = rootProject.file("config/spotbugs/exclude.xml")
    }

    tasks.withType(com.github.spotbugs.SpotBugsTask) {
        reports {
            xml.enabled = false
            html.enabled = true
        }
    }

    tasks.withType(CodeNarc) {
        configFile = rootProject.file("config/codenarc/ruleset.groovy")
    }

    pmd {
        ruleSetFiles = rootProject.files("config/pmd/ruleset.xml")
    }
}

```

</details>

I wtedy można je wywalić z tych `build.gradle` w modułach

2019-04-09 14:28 UTC, jplewa commented
Jakbyś znalazł łatwy sposób, żeby checkstyle i pmd generowały tylko htmle (bez xml), to by w sumie było spoko

2019-04-09 18:09 UTC, Sopel97 commented
teraz jest
- poprawiony ruleset dla pmd
- jedna lokacja dla configow
- stringi przy tych wyjatkach tak jak dzisiaj proponowalas
- poprawiony checkstyle
- w tym setterze zawsze mozna dac nazwy newStart, newEnd. Nie da sie zmienic patternu do wykrywania setterow (jesli zmiana to razem z bugfixem w ifie twoim)
- same html

2019-04-09 19:15 UTC, jplewa commented
Super!

Na wyjęcie pluginów do wspólnego `build.gradle` w roocie projektu patrzyłeś? (Tam w moim przedostatnim komentarzu dzięki magii htmla Ci wkleiłam rozwijalną sugestię, jak u mnie chyba działa)

Do `Papaya.java` myślę, że należy dodać na klasie:
`@SuppressWarnings({"checkstyle:HideUtilityClassConstructor", "PMD.UseUtilityClass"})`

Jeśli chodzi o tego settera, to myślę, że spokojnie można też dać `@SuppressWarnings("checkstyle:HiddenField")` na całej klasie albo konkretnie na metodzie  jakieś takie:
 
```
//CHECKSTYLE.OFF: HiddenField
<problematyczny setter>
//CHECKSTYLE.ON: HiddenField
```

[Tutaj](https://stackoverflow.com/a/4023351) więcej piszą, ale nie jestem pewna, czy mamy to już skonfigurowane

Nie nasza wina, że narzędzie inaczej postrzega temat niż my :)

2019-04-09 19:35 UTC, Sopel97 commented
zrobione

2019-04-09 20:40 UTC, jplewa commented on build.gradle
> +}
Uwaga, uwaga: newline na końcu pliku :stuck_out_tongue:

2019-04-09 20:46 UTC, jplewa commented on data/src/main/java/pl/edu/agh/papaya/model/LocalDateTimePeriod.java
>              throw new DateTimeException("Start date cannot be after the end date.");
A tu bym zmieniła na `throw new DateTimeException("Start date must be before the end date.");` i już nic nie będzie na nas ostrzegał

2019-04-10 19:02 UTC, jplewa approved these changes

2019-04-10 19:22 UTC, jplewa requested changes
W sumie #11 za moment wchodzi, to jeszcze dobrze by było zrobić rebase i upewnić się, że tam jest wszystko spoko (a coś się pewnie może konflikcić)

2019-04-10 19:35 UTC, jplewa commented
> W sumie #11 za moment wchodzi, to jeszcze dobrze by było zrobić rebase i upewnić się, że tam jest wszystko spoko (a coś się pewnie może konflikcić)

Aaalbo i nic się nie konflikci i chyba wszystko przechodzi, także nie ma problemu :)

2019-04-10 19:36 UTC, jplewa submitted a review, later dismissed

2019-04-10 19:49 UTC, jplewa approved these changes

2019-04-10 19:51 UTC, merged